import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import Navigation from "@/components/nav";
import "./globals.css";
import { NextFont } from "next/dist/compiled/@next/font";

const quicksand: NextFont = Quicksand({ weight: "500", subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Archilst",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>): JSX.Element {
	return (
		<html lang="en" className="scroll-smooth">
			<body
				className={`bg-gradient-to-b from-blue-500 via-light-blue-100 to-blue-500 bg-no-repeat ${quicksand.className}`}
			>
				<Navigation />
				{children}
			</body>
		</html>
	);
}
